### ISSUE TITLE
Question: Is the TelnetStream class implementing RFC854 or not?

### ISSUE THREAD

**Issue by rvdbreemen** [JAndrassy/TelnetStream#11]
I have been using your streamclass with my code, with great succes I might add.  

I just want to understand, you do NOT implement the RFC854 (https://tools.ietf.org/html/rfc854) specfication. Instead your class is a tcp wrapper class, that behaves like a serial stream (or any other stream for that matter).

Thus my question is: Am I correct it is basically a serial /stream over tcp implementation?

**Comment by JAndrassy** [comment]
> is a tcp wrapper class, that behaves like a serial stream (or any other stream for that matter).

yes and that is called Telnet. Telnet is a terminal over TCP as the RFC states. Negotiation is optional. you can use a Telnet client to connect to TelnetStream server.
