### ISSUE TITLE
New Compiling Issue

### ISSUE THREAD

**Issue by ghost** [JAndrassy/TelnetStream#16]
Ive been trying to compile [https://github.com/SensorsIot/ESP32-OTA.git](url) on arduinodroid, specifically the 

[https://github.com/SensorsIot/ESP32-OTA/blob/master/0TA_Template_Sketch_TelnetStream/0TA_Template_Sketch_TelnetStream.ino](url) 

code and i keep getting

`
/src/TelnetStream.h:27:13: error: cannot declare field 'TelnetStreamClass::server' to be of abstract type 'EthernetServer'
`

I think it may be cause of an update somewhere along the way, i'm sorry if this is the wrong way of doing this, i'm still learning, and have no clue where to start fixing this...

**Comment by JAndrassy** [comment]
that is a problem of the Server class in ESP32 Arduino core
https://github.com/espressif/arduino-esp32/pull/3607/files

ESP32 Arduino core has many problems with Arduino compatibility and this library is written to be multiplatform.
