### ISSUE TITLE
Error during compile: "undefined reference to `TelnetStream'"

### ISSUE THREAD

**Issue by NorthyIE** [JAndrassy/TelnetStream#18]
I ran into the same issue as this: https://github.com/jandrassy/TelnetStream/issues/17, so I am currently trying to use the git master version instead of the release.

This does unfortunately not work for me either, I get these errors during compile, even when simply trying to compile the "TelnetStreamEsp8266Test"-example (to make sure that the issue is not related to my coding:

`> Executing task: C:\Users\Northy\.platformio\penv\Scripts\platformio.exe run <

Processing d1_mini_lite (platform: espressif8266; board: d1_mini_lite; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini_lite.html
PLATFORM: Espressif 8266 (3.2.0) > WeMos D1 mini Lite
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.30002.0 (3.0.2)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - toolchain-xtensa 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 44 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <PubSubClient> 2.8.0
|-- <ArduinoMqttClient> 0.1.5
|-- <DHT sensor library> 1.4.3
|   |-- <Adafruit Unified Sensor> 1.1.4
|-- <Adafruit Unified Sensor> 1.1.4
|-- <Time> 1.6.1
|-- <ESP8266WiFi> 1.0
|-- <Ethernet> 2.0.0
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio\build\d1_mini_lite\src\main.cpp.o
Linking .pio\build\d1_mini_lite\firmware.elf
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o:(.text.setup+0x2c): undefined reference to `TelnetStream'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o:(.text.setup+0x30): undefined reference to `_ZN17TelnetStreamClass5beginEi'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o: in function `setup':
main.cpp:(.text.setup+0xfa): undefined reference to `_ZN17TelnetStreamClass5beginEi'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o:(.text.loop+0x8): undefined reference to `_ZN17TelnetStreamClass4readEv'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o:(.text.loop+0xc): undefined reference to `_ZN17TelnetStreamClass4stopEv'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o:(.text.loop+0x10): undefined reference to `_ZN17TelnetStreamClass5flushEv'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o:(.text.loop+0x26): undefined reference to `_ZN17TelnetStreamClass4readEv'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: .pio\build\d1_mini_lite\src\main.cpp.o: in function `loop':
main.cpp:(.text.loop+0x38): undefined reference to `_ZN17TelnetStreamClass4stopEv'
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: main.cpp:(.text.loop+0x59): undefined reference to `_ZN17TelnetStreamClass5flushEv'     
c:/users/northy/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: main.cpp:(.text.loop+0x62): undefined reference to `_ZN17TelnetStreamClass4stopEv'      
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\d1_mini_lite\firmware.elf] Error 1
================================================================================================= [FAILED] Took 2.93 seconds =================================================================================================`

**Comment by JAndrassy** [comment]
TelnetStream.cpp was not compiled
