### ISSUE TITLE
flush function returns void

### ISSUE THREAD

**Issue by Karijn** [JAndrassy/TelnetStream#2]
void TelnetStreamClass::flush() {
  if (disconnected())
    return;
  //return client.flush();
  // should read
  client.flush();
}

**Comment by JAndrassy** [comment]
yes. it is a 'copy-paste error'. and the compiler doesn't give me a warning

**Comment by mrWheel** [comment]
Hi JanDrassy,
Will you please replace line 59 in TelnetStream.cpp to read:

`client.flush()`

ESP8266 core 2.5.0 complaines about te return<value> in a void function ...

**Comment by JAndrassy** [comment]
done https://github.com/jandrassy/TelnetStream/commit/3f92765b9159fba9f19774f9992809baa604d33b
