### ISSUE TITLE
at some point telnetprint does not send anymore

### ISSUE THREAD

**Issue by peff74** [JAndrassy/TelnetStream#21]
I used TelnetPrint on some ESP32.
Now I wanted to use it on an ESP8266.
Here it happens that after some runtime a connection via port 23 can still be established, but no more data is sent from the ESP to the client.
I only use TelnetPrint.println TelnetPrint.print for debugging

My system
ESP8266 ESP01
ESP 2.7.4
ThingSpeak
ESP8266WebServer
ESP8266HTTPClient
ArduinoOTA

On the ESP32 this does not happen with the same code.
Is it possible that this is caused by WLAN interruptions? 
The ESPs are installed in an area where WLAN is only available at certain times.

**Comment by svdrummer** [comment]
Did you resolve the problem?

**Comment by svdrummer** [comment]
May as well close this as the OP has gone
