### ISSUE TITLE
Setting two telnet channels

### ISSUE THREAD

**Issue by svdrummer** [JAndrassy/TelnetStream#24]
Is it possible to declare two instances of TelnetStream?

I am sending data to several units and wanted a different channel for specific data, rather than using the serial port.
Esp32 serial port resets the micro each time you connect a terminal to the port. 

Ie 
TelnetStream Telnet1(23)
Telnet Stream Telnet2(100)

**Comment by JAndrassy** [comment]
yes

**Comment by svdrummer** [comment]
i can't seem to get it to compile. Must be the way i am configuring it.
As per the examples, i dont declare an object. 
I currently just do the following
TelnetStream.write(someMessage);
How would I declare two streams.? I have tried
TelnetStream Telnet1(23)
TelnetStream Telnet2(100)

**Comment by JAndrassy** [comment]
`TelnetStreamClass telnet(100);`
