### ISSUE TITLE
Overload/New Instantiate TelnetStream object

### ISSUE THREAD

**Issue by billbrach** [JAndrassy/TelnetStream#29]
Not a bug, just a suggestion to make your library easier to use whenever you have a lot of .print or .println of your object

It is a lot to type "TelnetStream.print(whatever I want to print)

Would be better to be able to do this:
    TelnetStream ts; // create new object
 and then be able to do:
    ts.print(whatever I want);

**Comment by JAndrassy** [comment]
since it is global object a simple name would easily collide.

`#define tx TelnetStream`
is always an option

**Comment by billbrach** [comment]
Using the #define method to use a shorter name works well, thanks
