### ISSUE TITLE
Please remove line 29 from TelnetStream.cpp

### ISSUE THREAD

**Issue by mrWheel** [JAndrassy/TelnetStream#3]
Will you please remove line 29 from TelnetStream.cpp?

Sometime someone will enter a capital “C” and than the connection is closed.
Maybe you can code a more exceptional exit like “quit” or .. “exit”.

Would be much appreciated!

It is a great library that I use in all of my esp projects!

**Comment by JAndrassy** [comment]
https://github.com/jandrassy/TelnetStream/commit/1294a9ee5cc9b1f7e51005091e351d60c8cddecf
