### ISSUE TITLE
Arduino OPTA

### ISSUE THREAD

**Issue by MauroKTM** [JAndrassy/TelnetStream#30]
it returns error when compile for Arduino OPTA

`/Users/xxx/Documents/Arduino/libraries/TelnetStream/src/TelnetStream.cpp: In member function 'boolean TelnetStreamClass::disconnected()':
/Users/xxx/Documents/Arduino/libraries/TelnetStream/src/TelnetStream.cpp:27:7: error: no match for 'operator!' (operand type is 'arduino::EthernetServer')
   if (!server)
       ^~~~~~~
/Users/xxx/Documents/Arduino/libraries/TelnetStream/src/TelnetStream.cpp:27:7: note: candidate: operator!(bool) <built-in>
/Users/xxx/Documents/Arduino/libraries/TelnetStream/src/TelnetStream.cpp:27:7: note:   no known conversion for argument 1 from 'arduino::EthernetServer' to 'bool'

exit status 1

Compilation error: exit status 1`

**Comment by JAndrassy** [comment]
modify the `#if` in `boolean TelnetStreamClass::disconnected() `

to
```
#if __has_include(<WiFiNINA.h>) || __has_include(<WiFi101.h>) || __has_include(<PortentaEthernet.h>)
```

**Comment by MauroKTM** [comment]
It works.

thank you!

**Comment by MauroKTM** [comment]
It compiles now, but it seems not starting any telnet server.
Any suggestion?
