### ISSUE TITLE
Pls add a client flush

### ISSUE THREAD

**Issue by arjenv** [JAndrassy/TelnetStream#36]
It so appears that at startup the client buffer is not empty. After some debugging the buffer had some 28 characters in the buffer containing meaningless info. As I 'poll' every 2 secs for a possible input (read) it took a while to react before the buffer was empty. Also after inputting a single character through Telnet it of course registers 3 chars, ending with \r\n (return & newline). That means that after a character read it has to poll again through the buffer to empty the \r\n

I added the following code:

while(TelnetStream.available())
        TelnetStream.read(); // empty buffer. Required because at startup the buffer is filled with garbage
                            // and after a single letter command there is still a return and Newline.

However some sort of client flush command would be nice.
Thanks

**Comment by JAndrassy** [comment]
flush() is a TX operation. it sends out the transmit buffer content even when the buffer is not full.

you can use `find` to skip incoming input with a timeout (set by `setTimeout`). to skip the rest of the line you can use `find('\n')`. it will read the \n too.

**Comment by arjenv** [comment]
ThankS
