### ISSUE TITLE
Industrial Shields M-Duino 21+ Board Manager Problem 'class EthernetServer' has no member named 'flush'

### ISSUE THREAD

**Issue by hnep339** [JAndrassy/TelnetStream#39]
Hi, I'm having compilation errors with the library.
I'm working on an Arduino Mega with an Ethernet shield that works with the standard Ethernet library.

However this is the errors I get when I try uploading the TelnetPrintEthTest example:

```
c:\Users\...\Documents\Arduino\libraries\TelnetStream\src\TelnetStream.cpp: In member function 'virtual void TelnetStreamClass::flush()':
c:\Users\...\Documents\Arduino\libraries\TelnetStream\src\TelnetStream.cpp:66:10: error: 'class EthernetServer' has no member named 'flush' server.flush();
```

**Comment by hnep339** [comment]
Okay, I think I was able to track down the problem:
I'm using an Arduino Mega that is build in an Industrial Shield module that has it's own Board Manager. I suspect that the library is not able to properly detect my board.
I'll investigate further and share my findings.

**Comment by JAndrassy** [comment]
it has outdated Arduino Core. Print.flush is missing

**Comment by hnep339** [comment]
It is indeed a problem with the custom board manager.

_I fixed it by replacing the Print.h from the custom board manager with the newest Print.h from the ArduinoCore-avr:
https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/Print.h_

Thank you!
