### ISSUE TITLE
Test if someone is connected

### ISSUE THREAD

**Issue by arjenv** [JAndrassy/TelnetStream#41]
Not an issue, but i was wondering if there is a command to test if someone is connected. I can test e.g.

while(TelnetStream.available()) ....

but is there a test to determine if anyone has even opened the telnet stream?

Got an application in which the telnet is scarcely used, so a test for a client would be more time conserving I guess....

Thanks!

**Comment by JAndrassy** [comment]
Arduino's WiFiServer / EthernetServer handles the connected clients for print, but has in general no function to know that there are some clients connected. It only relieves a client if the client sends some data. 

some networking libraries have `hasClient()`. It would be available if you use TelnetPrint,
