### ISSUE TITLE
Setting for more than one client

### ISSUE THREAD

**Issue by svdrummer** [JAndrassy/TelnetStream#6]
Can a setting be added to stream to more than one client?
Same data, send only.

**Comment by JAndrassy** [comment]
for which networking library do you need it? esp8266 or Ethernet?

**Comment by svdrummer** [comment]
Esp8266 (not 01 version) or esp32. Please.

**Comment by JAndrassy** [comment]
you can test it now

**Comment by svdrummer** [comment]
Any Examples? Still only accepts one client.

**Comment by JAndrassy** [comment]
it is already in release. 1.2.0 version
