### ISSUE TITLE
Error compiling TelnetStreamEthTest with EthernetENC

### ISSUE THREAD

**Issue by jandrassy** [jandrassy/TelnetStream#7]
[original issue](https://github.com/jandrassy/TelnetStream/issues/19) was hijacked with following posts.

**Comment by Staggeble** [comment]
I have issues while compiling the TelnetStream.h library with the latest Arduino 1.8.13.

error: missing binary operator before token "("
 #if __has_include(<EthernetENC.h>)

Is this issue linked with the above?

**Comment by jandrassy** [comment]
> I have issues while compiling the TelnetStream.h library with the latest Arduino IDE 1.8.13.
> 
> error: missing binary operator before token "("
> #if __has_include(<EthernetENC.h>)
> 
> Is this issue linked with the above?

the version of IDE doesn't matter. what MCU is it?

**Comment by Staggeble** [comment]
> > I have issues while compiling the TelnetStream.h library with the latest Arduino IDE 1.8.13.
> > error: missing binary operator before token "("
> > #if __has_include(<EthernetENC.h>)
> > Is this issue linked with the above?
> 
> the version of IDE doesn't matter. what MCU is it?

I am using an ESP-01S.

**Comment by jandrassy** [comment]
> I am using an ESP-01S.

this issue is about a different problem.
the example for esp8266 compiles without problems. 
what version of esp8266 arduino do you use?
did you change something in the library?

**Comment by Staggeble** [comment]
> > I am using an ESP-01S.
> 
> this issue is about a different problem.
> the example for esp8266 compiles without problems.
> what version of esp8266 arduino do you use?
> did you change something in the library?

Yesterday I pulled the latest master branch from GitHub.
https://github.com/esp8266/Arduino.git
I didn't modify anything. I will try if the example also works here.

**Comment by jandrassy** [comment]
> > > I am using an ESP-01S.
> > 
> > 
> > this issue is about a different problem.
> > the example for esp8266 compiles without problems.
> > what version of esp8266 arduino do you use?
> > did you change something in the library?
> 
> Yesterday I pulled the latest master branch from GitHub.
> https://github.com/esp8266/Arduino.git
> I didn't modify anything. I will try if the example also works here.

try fixed NetTypes.h

**Comment by Staggeble** [comment]
I believe the problem was at my side. The actual esp8266 Arduino library installed was version 2.3. Yesterday I updated it to 2.7.4 and it worked without any problem. I tried to install it via the .zip file, but I had to install it via the board manager.

**Comment by svdrummer** [comment]
Can we assume this issue is now closed? Seems the issue with the ESP board manager update resolved the issue.

**Comment by jandrassy** [comment]
> Can we assume this issue is now closed? Seems the issue with the ESP board manager update resolved the issue.

this is issue is not about esp

**Comment by svdrummer** [comment]
> > Can we assume this issue is now closed? Seems the issue with the ESP board manager update resolved the issue.
> 
> this is issue is not about esp

"I believe the problem was at my side. The actual esp8266 Arduino library installed was version 2.3. Yesterday I updated it to 2.7.4 and it worked without any problem. I tried to install it via the .zip file, but I had to install it via the board manager."

**Comment by jandrassy** [comment]
> > > Can we assume this issue is now closed? Seems the issue with the ESP board manager update resolved the issue.
> > 
> > 
> > this is issue is not about esp
> 
> "I believe the problem was at my side. The actual esp8266 Arduino library installed was version 2.3. Yesterday I updated it to 2.7.4 and it worked without any problem. I tried to install it via the .zip file, but I had to install it via the board manager."

you still didn't noticed that Staggeble hijacked the issue?
